on: [push, pull_request]

name: R-check

jobs:
  R-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        # - { os: windows-latest, r: 'release'}
        - { os: macOS-latest, r: 'release'}
        - { os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        continue-on-error: true
        run: |
          brew install poppler
      
      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo add-apt-repository -y ppa:cran/poppler
          sudo apt-get update
          sudo apt-get install -y libpoppler-cpp-dev libpoppler-dev poppler-utils

      # - name: Install Poppler on Windows
      #   if: runner.os == 'Windows'
      #   run: |
      #     choco install --no-progress poppler
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        if: runner.os != 'Windows'
        with:
          upload-snapshots: true

      # - name: Set pdfimages env for Windows
      #   run: echo "PDFIMAGER_PATH=$(where.exe pdfimages)" >> $GITHUB_ENV

      # - name: R Check on Windows
      #   uses: r-lib/actions/check-r-package@v2
      #   if: runner.os == 'Windows'
      #   with:
      #     upload-snapshots: true
